<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVx75Uu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVx75Uu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVx75Uu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVx75Uu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXVx75Uu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XVx75Uu',
    'container.build_id' => 'ceaa1d39',
    'container.build_time' => 1554720292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVx75Uu');
