<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3aF0D3j\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3aF0D3j/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3aF0D3j.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3aF0D3j\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3aF0D3j\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3aF0D3j',
    'container.build_id' => 'a7677193',
    'container.build_time' => 1555434942,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3aF0D3j');
