<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHU9ZDNb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHU9ZDNb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHU9ZDNb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHU9ZDNb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHU9ZDNb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HU9ZDNb',
    'container.build_id' => '087f97ef',
    'container.build_time' => 1555697863,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHU9ZDNb');
